# Generated by Django 4.1.2 on 2022-12-30 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usaha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(max_length=40)),
                ('tahun18', models.IntegerField(null=True)),
                ('tahun19', models.IntegerField(null=True)),
                ('koordinat', models.TextField()),
                ('detail', models.TextField()),
                ('usaha_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pengolahan_app.usaha')),
            ],
        ),
    ]
